export const MINING_COMPANIES_SEED = [
  { name: "BHP Billiton", email: "hr@bhp.com.au", state: "WA" },
  { name: "Rio Tinto", email: "recruitment@riotinto.com.au", state: "WA" },
  { name: "Fortescue Metals Group", email: "careers@fmgl.com.au", state: "WA" },
  { name: "Newcrest Mining", email: "hr@newcrest.com.au", state: "VIC" },
  { name: "OZ Minerals", email: "recruitment@ozminerals.com.au", state: "SA" },
  { name: "Evolution Mining", email: "hr@evolutionmining.com.au", state: "NSW" },
  { name: "Northern Star Resources", email: "careers@nsrltd.com.au", state: "WA" },
  { name: "Sandfire Resources", email: "hr@sandfire.com.au", state: "WA" },
  { name: "Independence Group", email: "recruitment@igo.com.au", state: "WA" },
  { name: "Iluka Resources", email: "hr@iluka.com", state: "WA" },
  { name: "South32", email: "careers@south32.net", state: "WA" },
  { name: "Mineral Resources", email: "hr@mineralresources.com.au", state: "WA" },
  { name: "Regis Resources", email: "recruitment@regisresources.com.au", state: "WA" },
  { name: "Saracen Mineral Mines", email: "hr@saracen.com.au", state: "WA" },
  { name: "Pilbara Minerals", email: "careers@pilbaraminerals.com.au", state: "WA" },
  { name: "Lynas Rare Earths", email: "hr@lynasre.com.au", state: "WA" },
  { name: "Whitehaven Coal", email: "recruitment@whitehavencoal.com.au", state: "NSW" },
  { name: "New Hope Corporation", email: "hr@newhopegroup.com.au", state: "QLD" },
  { name: "Yancoal Australia", email: "careers@yancoal.com.au", state: "NSW" },
  { name: "Coronado Global Resources", email: "hr@coronadoglobal.com.au", state: "QLD" },
];
